# Generated by Django 4.2.27 on 2026-01-11 22:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
